In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
print(a)

[-1.08287243 -0.0608992   1.23507862 -0.80138361 -0.85732855]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-1.08287243 -0.0608992   1.23507862 -0.80138361 -0.85732855]


In [6]:
print(np.dot(a,a.T))

4.078968542144018


In [7]:
a = np.random.randn(5,1)

In [8]:
print(a)

[[ 0.05095992]
 [-0.30516153]
 [ 0.53682799]
 [ 1.12233473]
 [ 0.74286565]]


In [9]:
print(a.T)

[[ 0.05095992 -0.30516153  0.53682799  1.12233473  0.74286565]]


In [10]:
print(np.dot(a,a.T))

[[ 0.00259691 -0.01555101  0.02735671  0.05719409  0.03785637]
 [-0.01555101  0.09312356 -0.16381925 -0.34249339 -0.22669402]
 [ 0.02735671 -0.16381925  0.28818429  0.6025007   0.39879107]
 [ 0.05719409 -0.34249339  0.6025007   1.25963525  0.83374392]
 [ 0.03785637 -0.22669402  0.39879107  0.83374392  0.55184937]]
